### ISSUE TITLE
Neuer Literatureintrag: Speichern-Button verschwindet, sobald ein Feld den Fokus verliert

### ISSUE THREAD

**Issue by WhiteFerrari666** [TimoSto/latexWissenschaftlichesArbeiten#1]
Mit Version 1.0.2 (heile):
neuen Literatureintrag anlegen, Felder ausfüllen, alles tutti

Mit Version 1.0.3 (kap0tt):
neuen Literatureintrag anlegen, ein Feld ausfüllen - sobald man das nächste Feld anwählt, verschwindet der "Speichern"-Button. Somit ist dann kein Speichern mehr möglich.

**Comment by TimoSto** [comment]
> Mit Version 1.0.2 (heile): neuen Literatureintrag anlegen, Felder ausfüllen, alles tutti
> 
> Mit Version 1.0.3 (kap0tt): neuen Literatureintrag anlegen, ein Feld ausfüllen - sobald man das nächste Feld anwählt, verschwindet der "Speichern"-Button. Somit ist dann kein Speichern mehr möglich.

Danke für den Hinweis! Die Buttons waren noch da, aber auch in weiß. Jetzt sollte es passen :)
